void createuser();
void login();
void logout();
void changepass();
void deleteuser();
vec loadfile();
vec1 databaseloadfile();
void savefile();
void savereport();
void saveHTMLreport();
void logrecord(string);
void viewfunc();
void loadmean(int);
void findrowmean(int, int, float ,double ,double);
void findcolmean(int, int, float ,double ,double);
void loadvar(int);
void findrowvar(int ,int ,float ,double ,double ,double);
void findcolvar(int ,int ,float ,double ,double ,double);
void loadstdv(int);
void findstdrowv(int ,int ,float ,double ,double ,double, double);
void findcolstdv(int ,int ,float ,double ,double ,double, double);
void loadcorr(int);
void findcolsum12(int ,int ,double);
void findcorrelation(int ,int ,float ,double ,double ,double);
void finddistinct();

